name: moroccan_cities
description: This package represents a utility package for accessing the data of all cities & regions in Morocco, so you can have the option to use it in your app directly without having to search for it or loading it from a remote source via an http request as an example.
version: 1.2.0
repository: https://github.com/anasfik/moroccan_cities

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
